name: Modules Split

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'

  pull_request: null

  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  moduleSplit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - path: 'admin'
            repository: 'ti-module-admin'
          - path: 'main'
            repository: 'ti-module-main'
          - path: 'system'
            repository: 'ti-module-system'

    steps:
      - uses: actions/checkout@v2

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Split ${{ matrix.package.path }} module into repository ${{ matrix.package.repository }}
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          branch: ${GITHUB_REF#refs/heads/}

          # ↓ split "app/admin" directory
          package_directory: 'app/${{ matrix.package.path }}'

          # ↓ into https://github.com/tastyigniter/ti-module-admin repository
          repository_organization: 'tastyigniter'
          repository_name: '${{ matrix.package.repository }}'

          # ↓ the user signed under the split commit
          user_name: "Sam Poyigi"
          user_email: "6567634+sampoyigi@users.noreply.github.com"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        name: Split tag of ${{ matrix.package.path }} module into repository ${{ matrix.package.repository }}
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "app/admin" directory
          package_directory: 'app/${{ matrix.package.path }}'

          # ↓ into https://github.com/tastyigniter/ti-module-admin repository
          repository_organization: 'tastyigniter'
          repository_name: '${{ matrix.package.repository }}'

          # ↓ the user signed under the split commit
          user_name: "Sam Poyigi"
          user_email: "6567634+sampoyigi@users.noreply.github.com"
