name: Tests

on:
  push:
    branches:
      - master
      - develop
      - tests
  pull_request:

jobs:
  PHPUnitTests:
#    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
#        os: [ubuntu-latest, windows-latest]
        php: ['7.4', '8.0']
        db: ['mysql:5.7', 'mysql:8.0', mariadb]
        include:
          - db: 'mysql:5.7'
            dbName: 'MySQL 5.7'
          - db: 'mysql:8.0'
            dbName: 'MySQL 8'
          - db: mariadb
            dbName: 'MariaDB'
      fail-fast: false

    services:
      mysql:
        image: ${{ matrix.db }}
        ports:
          - 13306:3306

    name: 'PHPUnit Tests ${{ matrix.php }} / ${{ matrix.dbName }}'

    steps:
      - name: Checkout changes
        uses: actions/checkout@v1

      - name: Create MySQL Database
        run: |
          sudo systemctl start mysql
          mysql -uroot -proot -e 'CREATE DATABASE ti_test;' --port 13306

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, gd, xml, sqlite

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --no-suggest --no-scripts

      - name: Reset TastyIgniter library
        run: |
          git reset --hard HEAD
          rm -rf ./vendor/tastyigniter/flame
          wget https://github.com/tastyigniter/flame/archive/master.zip -O ./vendor/tastyigniter/master.zip
          unzip ./vendor/tastyigniter/master.zip -d ./vendor/tastyigniter
          mv ./vendor/tastyigniter/flame-master ./vendor/tastyigniter/flame
          composer dump-autoload
        env:
          DB_PORT: 13306
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_PREFIX: ${{ matrix.prefix }}
          IGNITER_LOCATION_MODE: multiple

      - name: Run composer post-update scripts
        run: |
          php artisan key:generate --force
          php artisan igniter:install --no-interaction
          php artisan igniter:util set version
          php artisan package:discover

      - name: Run PHPUnit Test Suite
        run: ./vendor/bin/phpunit
